import { useState } from "react";
import { Button } from "@/components/ui/button";
import { NeuraalLogo } from "@/components/ui/NeuraalLogo";
import { useNavigate } from "react-router-dom";
import {
  ArrowLeft,
  LayoutGrid,
  ChevronLeft,
  ChevronRight,
  RotateCcw,
  Check,
  X,
  Sparkles,
  Plus,
} from "lucide-react";
import { toast } from "sonner";

interface FlashcardType {
  id: string;
  front: string;
  back: string;
  topic: string;
  mastered: boolean;
}

export default function Flashcards() {
  const navigate = useNavigate();
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [showAnswer, setShowAnswer] = useState(false);

  // Mock flashcards (will be generated by LLM)
  const [flashcards, setFlashcards] = useState<FlashcardType[]>([
    {
      id: "1",
      front: "What is the mechanism of action of aspirin?",
      back: "Aspirin irreversibly inhibits cyclooxygenase (COX-1 and COX-2) enzymes, preventing the synthesis of prostaglandins and thromboxanes involved in inflammation and platelet aggregation.",
      topic: "Pharmacology",
      mastered: false,
    },
    {
      id: "2",
      front: "Define pharmacokinetics",
      back: "Pharmacokinetics is the study of how the body affects a drug, including its absorption, distribution, metabolism, and excretion (ADME).",
      topic: "Pharmacology",
      mastered: false,
    },
    {
      id: "3",
      front: "What is bioavailability?",
      back: "Bioavailability is the fraction of an administered dose of unchanged drug that reaches the systemic circulation. For IV administration, bioavailability is 100%.",
      topic: "Pharmacokinetics",
      mastered: true,
    },
    {
      id: "4",
      front: "List the four phases of drug metabolism",
      back: "Phase 0: Uptake transporters\nPhase I: Oxidation, reduction, hydrolysis (mainly CYP450)\nPhase II: Conjugation reactions\nPhase III: Efflux transporters",
      topic: "Drug Metabolism",
      mastered: false,
    },
  ]);

  const currentCard = flashcards[currentIndex];
  const totalCards = flashcards.length;
  const masteredCount = flashcards.filter((c) => c.mastered).length;

  const handleFlip = () => {
    setIsFlipped(!isFlipped);
    setShowAnswer(true);
  };

  const handleNext = () => {
    if (currentIndex < totalCards - 1) {
      setCurrentIndex((prev) => prev + 1);
      setIsFlipped(false);
      setShowAnswer(false);
    }
  };

  const handlePrev = () => {
    if (currentIndex > 0) {
      setCurrentIndex((prev) => prev - 1);
      setIsFlipped(false);
      setShowAnswer(false);
    }
  };

  const handleMarkMastered = () => {
    setFlashcards((prev) =>
      prev.map((card) =>
        card.id === currentCard.id ? { ...card, mastered: true } : card
      )
    );
    toast.success("Card marked as mastered!");
    handleNext();
  };

  const handleNeedsPractice = () => {
    setFlashcards((prev) =>
      prev.map((card) =>
        card.id === currentCard.id ? { ...card, mastered: false } : card
      )
    );
    handleNext();
  };

  const handleShuffle = () => {
    const shuffled = [...flashcards].sort(() => Math.random() - 0.5);
    setFlashcards(shuffled);
    setCurrentIndex(0);
    setIsFlipped(false);
    setShowAnswer(false);
    toast.success("Cards shuffled!");
  };

  return (
    <div className="min-h-screen bg-background flex flex-col">
      {/* Header */}
      <header className="sticky top-0 z-50 neuraal-glass border-b border-border/50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="icon" onClick={() => navigate("/dashboard")}>
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-lg bg-neuraal-emerald/10">
                <LayoutGrid className="w-5 h-5 text-neuraal-emerald" />
              </div>
              <h1 className="font-display font-semibold">Flashcards</h1>
            </div>
          </div>
          <NeuraalLogo size="sm" showText={false} />
        </div>
      </header>

      {/* Progress & Stats */}
      <div className="container mx-auto px-4 py-4 max-w-2xl">
        <div className="flex items-center justify-between mb-4">
          <span className="text-sm text-muted-foreground">
            Card {currentIndex + 1} of {totalCards}
          </span>
          <div className="flex items-center gap-2 text-sm">
            <span className="text-neuraal-emerald font-medium">{masteredCount} mastered</span>
            <span className="text-muted-foreground">•</span>
            <span className="text-muted-foreground">{totalCards - masteredCount} remaining</span>
          </div>
        </div>
        <div className="h-2 bg-secondary rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-neuraal-emerald to-accent transition-all duration-500"
            style={{ width: `${(masteredCount / totalCards) * 100}%` }}
          />
        </div>
      </div>

      {/* Main Card Area */}
      <main className="flex-1 flex items-center justify-center px-4 py-8">
        <div className="w-full max-w-lg">
          {/* Topic badge */}
          <div className="text-center mb-4">
            <span className="inline-flex px-3 py-1 rounded-full bg-secondary text-sm">
              {currentCard.topic}
            </span>
          </div>

          {/* Flashcard */}
          <div
            className="relative cursor-pointer perspective-1000"
            onClick={handleFlip}
            style={{ minHeight: "300px" }}
          >
            <div
              className={`absolute inset-0 transition-all duration-500 preserve-3d ${
                isFlipped ? "rotate-y-180" : ""
              }`}
              style={{
                transformStyle: "preserve-3d",
                transform: isFlipped ? "rotateY(180deg)" : "rotateY(0deg)",
              }}
            >
              {/* Front */}
              <div
                className="absolute inset-0 neuraal-card p-8 flex flex-col items-center justify-center text-center backface-hidden"
                style={{ backfaceVisibility: "hidden" }}
              >
                <div className="text-xs text-muted-foreground uppercase tracking-wide mb-4">
                  Question
                </div>
                <p className="text-xl font-display font-semibold">
                  {currentCard.front}
                </p>
                <div className="mt-6 text-sm text-muted-foreground">
                  Tap to reveal answer
                </div>
              </div>

              {/* Back */}
              <div
                className="absolute inset-0 neuraal-card p-8 flex flex-col items-center justify-center text-center bg-gradient-to-br from-primary/5 to-accent/5"
                style={{
                  backfaceVisibility: "hidden",
                  transform: "rotateY(180deg)",
                }}
              >
                <div className="text-xs text-primary uppercase tracking-wide mb-4">
                  Answer
                </div>
                <p className="text-lg whitespace-pre-line">
                  {currentCard.back}
                </p>
              </div>
            </div>
          </div>

          {/* Action buttons (show after flip) */}
          {showAnswer && (
            <div className="mt-6 flex items-center justify-center gap-4 animate-fade-up">
              <Button
                variant="outline"
                size="lg"
                onClick={handleNeedsPractice}
                className="flex-1 border-destructive/50 hover:bg-destructive/10"
              >
                <X className="w-5 h-5 mr-2 text-destructive" />
                Needs Practice
              </Button>
              <Button
                variant="outline"
                size="lg"
                onClick={handleMarkMastered}
                className="flex-1 border-neuraal-emerald/50 hover:bg-neuraal-emerald/10"
              >
                <Check className="w-5 h-5 mr-2 text-neuraal-emerald" />
                Got It
              </Button>
            </div>
          )}

          {/* Navigation */}
          <div className="mt-6 flex items-center justify-between">
            <Button
              variant="ghost"
              size="icon"
              onClick={handlePrev}
              disabled={currentIndex === 0}
            >
              <ChevronLeft className="w-6 h-6" />
            </Button>

            <div className="flex items-center gap-2">
              <Button variant="ghost" size="sm" onClick={handleShuffle}>
                <RotateCcw className="w-4 h-4 mr-1" />
                Shuffle
              </Button>
            </div>

            <Button
              variant="ghost"
              size="icon"
              onClick={handleNext}
              disabled={currentIndex === totalCards - 1}
            >
              <ChevronRight className="w-6 h-6" />
            </Button>
          </div>
        </div>
      </main>

      {/* Bottom action */}
      <footer className="p-4 border-t border-border">
        <div className="container mx-auto max-w-lg">
          <Button variant="outline" className="w-full" onClick={() => navigate("/upload")}>
            <Plus className="w-4 h-4 mr-2" />
            Generate More Flashcards
          </Button>
        </div>
      </footer>
    </div>
  );
}