import { useState } from "react";
import { Button } from "@/components/ui/button";
import { NeuraalLogo } from "@/components/ui/NeuraalLogo";
import { useNavigate } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import {
  ArrowLeft,
  Target,
  Play,
  Clock,
  BookOpen,
  ChevronRight,
  Check,
  X,
  Award,
  RotateCcw,
  Crown,
} from "lucide-react";
import { toast } from "sonner";

type QuizState = "setup" | "active" | "review";

interface Question {
  id: string;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  topic: string;
}

export default function Quiz() {
  const navigate = useNavigate();
  const { user } = useAuth();
  const [state, setState] = useState<QuizState>("setup");
  const [difficulty, setDifficulty] = useState<"easy" | "moderate" | "hard">("moderate");
  const [questionCount, setQuestionCount] = useState(10);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [answers, setAnswers] = useState<(number | null)[]>([]);
  const [showExplanation, setShowExplanation] = useState(false);

  // Mock questions (will be generated by LLM)
  const questions: Question[] = [
    {
      id: "1",
      question: "Which of the following is the primary mechanism of action of aspirin?",
      options: [
        "Inhibition of COX-1 and COX-2 enzymes",
        "Activation of opioid receptors",
        "Blocking sodium channels",
        "Stimulating dopamine release",
      ],
      correctAnswer: 0,
      explanation: "Aspirin irreversibly inhibits cyclooxygenase (COX) enzymes, preventing the synthesis of prostaglandins and thromboxanes.",
      topic: "Pharmacology",
    },
    {
      id: "2",
      question: "What is the half-life of aspirin in the body?",
      options: ["15-20 minutes", "2-3 hours", "6-8 hours", "24 hours"],
      correctAnswer: 0,
      explanation: "Aspirin has a very short half-life of about 15-20 minutes, but its effects last longer due to irreversible enzyme inhibition.",
      topic: "Pharmacokinetics",
    },
    {
      id: "3",
      question: "Which condition is aspirin commonly used to prevent?",
      options: [
        "Bacterial infections",
        "Cardiovascular events",
        "Viral infections",
        "Fungal infections",
      ],
      correctAnswer: 1,
      explanation: "Low-dose aspirin is widely used for secondary prevention of cardiovascular events due to its antiplatelet effects.",
      topic: "Therapeutics",
    },
  ];

  const currentQuestion = questions[currentIndex];
  const totalQuestions = questions.length;
  const score = answers.filter((a, i) => a === questions[i]?.correctAnswer).length;

  const handleStartQuiz = () => {
    setState("active");
    setAnswers(new Array(questions.length).fill(null));
    toast.success("Quiz started! Good luck!");
  };

  const handleSelectAnswer = (optionIndex: number) => {
    if (selectedAnswer !== null) return;
    setSelectedAnswer(optionIndex);
    setShowExplanation(true);

    const newAnswers = [...answers];
    newAnswers[currentIndex] = optionIndex;
    setAnswers(newAnswers);
  };

  const handleNext = () => {
    if (currentIndex < totalQuestions - 1) {
      setCurrentIndex((prev) => prev + 1);
      setSelectedAnswer(null);
      setShowExplanation(false);
    } else {
      setState("review");
    }
  };

  const handleRetry = () => {
    setState("setup");
    setCurrentIndex(0);
    setSelectedAnswer(null);
    setShowExplanation(false);
    setAnswers([]);
  };

  const renderSetup = () => (
    <div className="container mx-auto px-4 py-8 max-w-lg">
      <div className="text-center mb-8">
        <div className="inline-flex p-4 rounded-2xl bg-neuraal-amber/10 mb-4">
          <Target className="w-8 h-8 text-neuraal-amber" />
        </div>
        <h2 className="text-2xl font-display font-bold mb-2">Quiz Setup</h2>
        <p className="text-muted-foreground">
          Practice with exam-style questions from your notes
        </p>
      </div>

      {/* Difficulty */}
      <div className="neuraal-card p-6 mb-4">
        <h3 className="font-semibold mb-3 flex items-center gap-2">
          <BookOpen className="w-4 h-4" />
          Difficulty
        </h3>
        <div className="grid grid-cols-3 gap-2">
          {(["easy", "moderate", "hard"] as const).map((level) => (
            <button
              key={level}
              onClick={() => setDifficulty(level)}
              className={`py-3 rounded-lg text-sm font-medium capitalize transition-all ${
                difficulty === level
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary hover:bg-secondary/80"
              }`}
            >
              {level}
            </button>
          ))}
        </div>
      </div>

      {/* Question count */}
      <div className="neuraal-card p-6 mb-4">
        <h3 className="font-semibold mb-3 flex items-center gap-2">
          <Target className="w-4 h-4" />
          Number of Questions
        </h3>
        <div className="grid grid-cols-4 gap-2">
          {[5, 10, 15, 20].map((count) => (
            <button
              key={count}
              onClick={() => setQuestionCount(count)}
              className={`py-3 rounded-lg text-sm font-medium transition-all ${
                questionCount === count
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary hover:bg-secondary/80"
              }`}
            >
              {count}
            </button>
          ))}
        </div>
      </div>

      {/* Timed mode (premium) */}
      <div className="neuraal-card p-6 mb-6">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Clock className="w-5 h-5 text-muted-foreground" />
            <div>
              <h3 className="font-semibold">Timed Mode</h3>
              <p className="text-xs text-muted-foreground">Simulate exam conditions</p>
            </div>
          </div>
          {user?.tier === "premium" ? (
            <Button variant="outline" size="sm">
              Enable
            </Button>
          ) : (
            <div className="flex items-center gap-1.5 text-xs text-neuraal-amber">
              <Crown className="w-3.5 h-3.5" />
              Premium
            </div>
          )}
        </div>
      </div>

      <Button variant="gradient" size="lg" className="w-full" onClick={handleStartQuiz}>
        <Play className="w-5 h-5 mr-2" />
        Start Quiz
      </Button>
    </div>
  );

  const renderActive = () => (
    <div className="container mx-auto px-4 py-6 max-w-2xl">
      {/* Progress */}
      <div className="mb-6">
        <div className="flex items-center justify-between mb-2">
          <span className="text-sm text-muted-foreground">
            Question {currentIndex + 1} of {totalQuestions}
          </span>
          <span className="text-sm font-medium">{currentQuestion.topic}</span>
        </div>
        <div className="h-2 bg-secondary rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-primary to-accent transition-all duration-500"
            style={{ width: `${((currentIndex + 1) / totalQuestions) * 100}%` }}
          />
        </div>
      </div>

      {/* Question */}
      <div className="neuraal-card p-6 mb-6">
        <h2 className="text-xl font-display font-semibold mb-6">
          {currentQuestion.question}
        </h2>

        <div className="space-y-3">
          {currentQuestion.options.map((option, index) => {
            const isSelected = selectedAnswer === index;
            const isCorrect = index === currentQuestion.correctAnswer;
            const showResult = selectedAnswer !== null;

            return (
              <button
                key={index}
                onClick={() => handleSelectAnswer(index)}
                disabled={selectedAnswer !== null}
                className={`w-full p-4 rounded-xl border-2 text-left transition-all ${
                  showResult
                    ? isCorrect
                      ? "border-neuraal-emerald bg-neuraal-emerald/10"
                      : isSelected
                      ? "border-destructive bg-destructive/10"
                      : "border-border opacity-50"
                    : isSelected
                    ? "border-primary bg-primary/5"
                    : "border-border hover:border-primary/50"
                }`}
              >
                <div className="flex items-center gap-3">
                  <div
                    className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-medium ${
                      showResult
                        ? isCorrect
                          ? "bg-neuraal-emerald text-white"
                          : isSelected
                          ? "bg-destructive text-white"
                          : "bg-secondary"
                        : isSelected
                        ? "bg-primary text-primary-foreground"
                        : "bg-secondary"
                    }`}
                  >
                    {showResult ? (
                      isCorrect ? (
                        <Check className="w-4 h-4" />
                      ) : isSelected ? (
                        <X className="w-4 h-4" />
                      ) : (
                        String.fromCharCode(65 + index)
                      )
                    ) : (
                      String.fromCharCode(65 + index)
                    )}
                  </div>
                  <span>{option}</span>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* Explanation */}
      {showExplanation && (
        <div className="neuraal-card p-6 mb-6 bg-accent/5 border-accent/20">
          <h3 className="font-semibold mb-2 flex items-center gap-2">
            <BookOpen className="w-4 h-4 text-accent" />
            Explanation
          </h3>
          <p className="text-muted-foreground">{currentQuestion.explanation}</p>
        </div>
      )}

      {/* Next button */}
      {selectedAnswer !== null && (
        <Button variant="gradient" size="lg" className="w-full" onClick={handleNext}>
          {currentIndex < totalQuestions - 1 ? (
            <>
              Next Question
              <ChevronRight className="w-5 h-5 ml-1" />
            </>
          ) : (
            <>
              See Results
              <Award className="w-5 h-5 ml-2" />
            </>
          )}
        </Button>
      )}
    </div>
  );

  const renderReview = () => {
    const percentage = Math.round((score / totalQuestions) * 100);

    return (
      <div className="container mx-auto px-4 py-8 max-w-lg text-center">
        <div className="inline-flex p-6 rounded-full bg-gradient-to-r from-primary/20 to-accent/20 mb-6">
          <Award className="w-16 h-16 text-primary" />
        </div>

        <h2 className="text-3xl font-display font-bold mb-2">Quiz Complete!</h2>
        <p className="text-muted-foreground mb-8">Here's how you did:</p>

        {/* Score */}
        <div className="neuraal-card p-8 mb-6">
          <div className="text-5xl font-display font-bold neuraal-gradient-text mb-2">
            {percentage}%
          </div>
          <div className="text-lg text-muted-foreground">
            {score} out of {totalQuestions} correct
          </div>

          {/* Performance message */}
          <div className="mt-4 p-3 rounded-lg bg-secondary">
            {percentage >= 80 ? (
              <span className="text-neuraal-emerald">🎉 Excellent work!</span>
            ) : percentage >= 60 ? (
              <span className="text-neuraal-amber">👍 Good effort! Keep practicing.</span>
            ) : (
              <span className="text-muted-foreground">📚 Review the topics and try again.</span>
            )}
          </div>
        </div>

        {/* Actions */}
        <div className="space-y-3">
          <Button variant="gradient" size="lg" className="w-full" onClick={handleRetry}>
            <RotateCcw className="w-5 h-5 mr-2" />
            Try Again
          </Button>
          <Button
            variant="outline"
            size="lg"
            className="w-full"
            onClick={() => navigate("/dashboard")}
          >
            Back to Dashboard
          </Button>
        </div>
      </div>
    );
  };

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-50 neuraal-glass border-b border-border/50">
        <div className="container mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Button
              variant="ghost"
              size="icon"
              onClick={() => (state === "active" ? null : navigate("/dashboard"))}
              disabled={state === "active"}
            >
              <ArrowLeft className="w-5 h-5" />
            </Button>
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-lg bg-neuraal-amber/10">
                <Target className="w-5 h-5 text-neuraal-amber" />
              </div>
              <h1 className="font-display font-semibold">Quizzes & Tests</h1>
            </div>
          </div>
          <NeuraalLogo size="sm" showText={false} />
        </div>
      </header>

      <main>
        {state === "setup" && renderSetup()}
        {state === "active" && renderActive()}
        {state === "review" && renderReview()}
      </main>
    </div>
  );
}